// stacks/vuejs/src/components/CellsColumn.vue
<script setup lang="ts">
import { computed } from "vue";
import { Path, Line, filterLines } from "@reactivity-comparison/pivoting";
import CellWrapper from "./CellWrapper.vue";

type Props = {
  pathRows: Path[];
  lines: Line[];
  rowsDepth: number;
  columnsDepth: number;
  columnPath: Path;
};
const { lines, pathRows, columnPath } = defineProps<Props>();

const filteredLines = computed(() => filterLines(columnPath.entries, lines));
</script>

<template>
  <CellWrapper
    v-for="rowPath in pathRows"
    :key="rowPath.offset"
    :pathEntries="rowPath.entries"
    :lines="filteredLines"
    :offset-x="columnPath.offset + rowsDepth"
    :offset-y="rowPath.offset + columnsDepth"
  ></CellWrapper>
</template>

<style scoped></style>

// stacks/react-observable/src/grid/internals/CellsColumn.tsx
import { Fragment } from "react/jsx-runtime";
import {
  Line,
  Path,
  filterLines,
  probeCall,
} from "@reactivity-comparison/pivoting";
import { BehaviorSubject } from "rxjs";
import { useComputed } from "../../observables/useComputed";
import CellsWrapper from "./CellWrapper";

type Props = {
  pathRows: Path[];
  linesSubject: BehaviorSubject<Line[]>;
  rowsDepth: number;
  columnsDepth: number;
  columnPath: Path;
};

export default function CellsColumn(props: Props) {
  probeCall(CellsColumn.name);
  const { pathRows, linesSubject, rowsDepth, columnsDepth, columnPath } = props;
  const filteredLinesSubject = useComputed(
    (lines) => filterLines(columnPath.entries, lines),
    [linesSubject]
  );
  return (
    <Fragment key={columnPath.offset}>
      {pathRows.map((rowPath) => (
        <CellsWrapper
          key={rowPath.offset}
          entries={rowPath.entries}
          linesSubject={filteredLinesSubject}
          offsetX={columnPath.offset + rowsDepth}
          offsetY={rowPath.offset + columnsDepth}
        />
      ))}
    </Fragment>
  );
}
