// stacks/vuejs/src/components/Cells.vue
<script setup lang="ts">
import { computed } from "vue";
import {
  computePaths,
  Line,
  HeaderTree,
} from "@reactivity-comparison/pivoting";
import CellsColumn from "./CellsColumn.vue";

type Props = {
  columns: HeaderTree[];
  rows: HeaderTree[];
  lines: Line[];
  rowsDepth: number;
  columnsDepth: number;
};
const { columns, rows, lines, rowsDepth, columnsDepth } = defineProps<Props>();

const pathColumns = computed(() => computePaths(columns));
const pathRows = computed(() => computePaths(rows));
</script>

<template>
  <CellsColumn
    v-for="columnPath in pathColumns"
    :key="columnPath.offset"
    :path-rows="pathRows"
    :column-path="columnPath"
    :lines="lines"
    :rows-depth="rowsDepth"
    :columns-depth="columnsDepth"
  ></CellsColumn>
</template>

<style scoped></style>

// stacks/react-observable/src/grid/internals/Cells.tsx
import {
  HeaderTree,
  Line,
  computePaths,
  probeCall,
} from "@reactivity-comparison/pivoting";
import { BehaviorSubject } from "rxjs";
import CellsColumn from "./CellsColumn";

type Props = {
  columns: HeaderTree[];
  rows: HeaderTree[];
  linesSubject: BehaviorSubject<Line[]>;
  rowsDepth: number;
  columnsDepth: number;
};

export default function Cells(props: Props) {
  probeCall(Cells.name);
  const { columns, rows, linesSubject, rowsDepth, columnsDepth } = props;
  const pathColumns = computePaths(columns);
  const pathRows = computePaths(rows);
  return (
    <>
      {pathColumns.map((columnPath) => {
        return (
          <CellsColumn
            key={columnPath.offset}
            pathRows={pathRows}
            columnPath={columnPath}
            columnsDepth={columnsDepth}
            linesSubject={linesSubject}
            rowsDepth={rowsDepth}
          />
        );
      })}
    </>
  );
}
