// stacks/vuejs/src/components/CellWrapper.vue
<script setup lang="ts">
import { computeValue, Line, Path } from "@reactivity-comparison/pivoting";
import Cell from "./Cell.vue";

type Props = {
  pathEntries: Path["entries"];
  lines: Line[];
  offsetX: number;
  offsetY: number;
};
const { pathEntries, lines, offsetX, offsetY } = defineProps<Props>();
</script>

<template>
  <Cell
    :value="computeValue(pathEntries, lines)"
    :offset-x="offsetX"
    :offset-y="offsetY"
  ></Cell>
</template>

<style scoped></style>

// stacks/react-observable/src/grid/internals/CellWrapper.tsx
import {
  Line,
  Path,
  computeValue,
  probeCall,
} from "@reactivity-comparison/pivoting";
import Cell from "./Cell";
import { BehaviorSubject } from "rxjs";
import { useWatch } from "../../observables/useWatch";
import { useComputed } from "../../observables/useComputed";

type Props = {
  entries: Path["entries"];
  linesSubject: BehaviorSubject<Line[]>;
  offsetX: number;
  offsetY: number;
};

export default function CellsWrapper(props: Props) {
  probeCall(CellsWrapper.name);
  const { entries, linesSubject, offsetX, offsetY } = props;
  const valueSubject = useComputed(
    (lines) => computeValue(entries, lines),
    [linesSubject]
  );
  const value = useWatch(valueSubject);
  return <Cell value={value} offsetX={offsetX} offsetY={offsetY} />;
}
