// stacks/vuejs/src/components/Header.vue
<script setup lang="ts">
import { computed } from "vue";
import { cellSize } from "@reactivity-comparison/pivoting";

type Props = {
  value: string;
  offsetX: number;
  offsetY: number;
  sizeX: number;
  sizeY: number;
};
const { value, offsetX, offsetY, sizeX, sizeY } = defineProps<Props>();

const style = computed(() => ({
  top: `${offsetY * cellSize}px`,
  left: `${offsetX * cellSize}px`,
  width: `${sizeX * cellSize}px`,
  height: `${sizeY * cellSize}px`,
}));
</script>

<template>
  <div class="header" :style="style">{{ value }}</div>
</template>

<style scoped>
.header {
  position: absolute;
  border: 1px solid #aaa;
  background-color: #eee;
  overflow: hidden;
}
</style>

// stacks/react-observable/src/grid/internals/Header.tsx
import { probeCall, cellSize } from "@reactivity-comparison/pivoting";

type Props = {
  value: string;
  offsetX: number;
  offsetY: number;
  sizeX: number;
  sizeY: number;
};

export default function Header(props: Props) {
  probeCall(Header.name);
  const { value, offsetX, offsetY, sizeX, sizeY } = props;
  return (
    <div
      style={{
        position: "absolute",
        top: offsetY * cellSize,
        left: offsetX * cellSize,
        width: sizeX * cellSize,
        height: sizeY * cellSize,
        border: "1px solid #aaa",
        backgroundColor: "#eee",
        overflow: "hidden",
      }}
    >
      {value}
    </div>
  );
}
