// stacks/react-observable/src/App.tsx
import { cloneDeep } from "lodash";
import Grid, { toHeaderId, toHeaders } from "./grid/Grid";
import { probeCall } from "@reactivity-comparison/pivoting";
import { usePipe } from "./observables/usePipe";
import { useWatch } from "./observables/useWatch";

const initialLines = [
  {
    headers: toHeaders({
      Country: "France",
      Town: "Mende",
      Product: "A",
    }),
    value: 1,
  },
  {
    headers: toHeaders({
      Country: "France",
      Town: "Mende",
      Product: "B",
    }),
    value: 2,
  },
  {
    headers: toHeaders({
      Country: "France",
      Town: "Lyon",
      Product: "B",
    }),
    value: 3,
  },
  {
    headers: toHeaders({
      Country: "United-States",
      Town: "New-York",
      Product: "A",
    }),
    value: 4,
  },
  {
    headers: toHeaders({
      Country: "United-States",
      Town: "New-York",
      Product: "C",
    }),
    value: 5,
  },
];

export default function App() {
  probeCall(App.name);
  const [linesSubject, setLines] = usePipe(initialLines);
  const lines = useWatch(linesSubject);

  return (
    <div>
      <div>
        <button
          onClick={() => {
            setLines(cloneDeep(lines));
          }}
        >
          Refresh data
        </button>
        <button
          onClick={() => {
            setLines([
              { ...lines[0], value: lines[0].value + 1 },
              ...lines.slice(1),
            ]);
          }}
        >
          Update one cell
        </button>
      </div>
      <div style={{ position: "relative" }}>
        <Grid
          lines={lines}
          rowHeaderIds={[toHeaderId("Country"), toHeaderId("Town")]}
          columnHeaderIds={[toHeaderId("Product")]}
        ></Grid>
      </div>
    </div>
  );
}

// stacks/vuejs/src/App.vue
<script setup lang="ts">
import { reactive } from "vue";
import { cloneDeep } from "lodash";
import Grid from "./components/Grid.vue";
import { toHeaders, toHeaderId } from "@reactivity-comparison/pivoting";

const lines = reactive([
  {
    headers: toHeaders({
      Country: "France",
      Town: "Mende",
      Product: "A",
    }),
    value: 1,
  },
  {
    headers: toHeaders({
      Country: "France",
      Town: "Mende",
      Product: "B",
    }),
    value: 2,
  },
  {
    headers: toHeaders({
      Country: "France",
      Town: "Lyon",
      Product: "B",
    }),
    value: 3,
  },
  {
    headers: toHeaders({
      Country: "United-States",
      Town: "New-York",
      Product: "A",
    }),
    value: 4,
  },
  {
    headers: toHeaders({
      Country: "United-States",
      Town: "New-York",
      Product: "C",
    }),
    value: 5,
  },
]);
const rowHeaderIds = reactive([toHeaderId("Country"), toHeaderId("Town")]);
const columnHeaderIds = reactive([toHeaderId("Product")]);

const refreshData = () => {
  for (let index = 0; index !== lines.length; ++index) {
    lines[index] = cloneDeep(lines[index]);
  }
};
const updateOneCell = () => {
  lines[0].value += 1;
};
</script>

<template>
  <div>
    <div>
      <button @click="refreshData">Refresh data</button>
      <button @click="updateOneCell">Update one cell</button>
    </div>
    <div class="grid">
      <Grid
        :lines="lines"
        :rowHeaderIds="rowHeaderIds"
        :columnHeaderIds="columnHeaderIds"
      ></Grid>
    </div>
  </div>
</template>

<style scoped>
.grid {
  position: relative;
}
</style>
