// stacks/react/src/grid/internals/Columns.tsx
import { Fragment } from "react/jsx-runtime";
import { HeaderSpanLevel, probeCall } from "@reactivity-comparison/pivoting";
import Header from "./Header";

type Props = {
  columnsSpans: HeaderSpanLevel[];
  rowsDepth: number;
};

export default function Columns(props: Props) {
  probeCall(Columns.name);
  const { columnsSpans, rowsDepth } = props;
  return (
    <>
      {columnsSpans.map((spanLevel, index) => (
        <Fragment key={index}>
          {spanLevel.map((span) => (
            <Header
              offsetX={span.backingTree.offset + rowsDepth}
              offsetY={index}
              sizeX={span.backingTree.size}
              sizeY={1}
              value={span.backingTree.value}
            />
          ))}
        </Fragment>
      ))}
    </>
  );
}

// stacks/vuejs/src/components/Columns.vue
<script setup lang="ts">
import { HeaderSpanLevel } from "@reactivity-comparison/pivoting";
import Header from "./Header.vue";

type Props = {
  columnsSpans: HeaderSpanLevel[];
  rowsDepth: number;
};
const { columnsSpans, rowsDepth } = defineProps<Props>();
</script>

<template>
  <template v-for="(spanLevel, index) in columnsSpans" :key="index"
    ><Header
      v-for="span in spanLevel"
      :key="span.backingTree.offset"
      :offset-x="span.backingTree.offset + rowsDepth"
      :offset-y="index"
      :size-x="span.backingTree.size"
      :size-y="1"
      :value="span.backingTree.value"
    ></Header
  ></template>
</template>

<style scoped></style>
