// stacks/react-observable/src/grid/Grid.tsx
import Cells from "./internals/Cells";
import Columns from "./internals/Columns";
import Rows from "./internals/Rows";
import {
  probeCall,
  HeaderId,
  Line,
  LineHeaders,
  buildHeaders,
  computeGridDimensions,
} from "@reactivity-comparison/pivoting";

type Props = {
  lines: Line[];
  columnHeaderIds: HeaderId[];
  rowHeaderIds: HeaderId[];
};

export default function Grid(props: Props) {
  probeCall(Grid.name);
  const { lines, columnHeaderIds, rowHeaderIds } = props;
  const columns = buildHeaders(lines, columnHeaderIds, 0);
  const rows = buildHeaders(lines, rowHeaderIds, 0);
  const { columnsDepth, rowsDepth } = computeGridDimensions(columns, rows);

  return (
    <div>
      <Rows rows={rows} offset={0} columnsDepth={columnsDepth} />
      <Columns columns={columns} offset={0} rowsDepth={rowsDepth} />
      <Cells
        rows={rows}
        columns={columns}
        lines={lines}
        rowsDepth={rowsDepth}
        columnsDepth={columnsDepth}
      />
    </div>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function toHeaders(headers: Record<string, string>): LineHeaders {
  return headers as LineHeaders;
}

// eslint-disable-next-line react-refresh/only-export-components
export function toHeaderId(headerId: string): HeaderId {
  return headerId as HeaderId;
}

// stacks/vuejs/src/components/Grid.vue
<script setup lang="ts">
import { computed } from "vue";
import {
  buildHeaders,
  computeGridDimensions,
  Line,
  HeaderId,
} from "@reactivity-comparison/pivoting";
import Cells from "./Cells.vue";
import Columns from "./Columns.vue";
import Rows from "./Rows.vue";

type Props = {
  lines: Line[];
  columnHeaderIds: HeaderId[];
  rowHeaderIds: HeaderId[];
};
const { lines, rowHeaderIds, columnHeaderIds } = defineProps<Props>();

const columns = computed(() => buildHeaders(lines, columnHeaderIds, 0));
const rows = computed(() => buildHeaders(lines, rowHeaderIds, 0));
const dimensions = computed(() =>
  computeGridDimensions(columns.value, rows.value)
);
</script>

<template>
  <Rows :rows="rows" :offset="0" :columns-depth="dimensions.columnsDepth" />
  <Columns :columns="columns" :offset="0" :rows-depth="dimensions.rowsDepth" />
  <Cells
    :rows="rows"
    :columns="columns"
    :lines="lines"
    :rows-depth="dimensions.rowsDepth"
    :columns-depth="dimensions.columnsDepth"
  />
</template>

<style scoped></style>
