// stacks/react-observable/src/grid/internals/Rows.tsx
import { Fragment } from "react/jsx-runtime";
import { HeaderTree, probeCall } from "@reactivity-comparison/pivoting";
import Header from "./Header";

type Props = {
  rows: HeaderTree[];
  offset: number;
  columnsDepth: number;
};

export default function Rows(props: Props) {
  probeCall(Rows.name);
  const { rows, offset, columnsDepth } = props;
  return (
    <>
      {rows.map((row) => (
        <Fragment key={row.value}>
          <Header
            offsetX={offset}
            offsetY={row.offset + columnsDepth}
            sizeX={1}
            sizeY={row.size}
            value={row.value}
          />
          <Rows
            rows={row.children}
            offset={offset + 1}
            columnsDepth={columnsDepth}
          />
        </Fragment>
      ))}
    </>
  );
}

// stacks/vuejs/src/components/Rows.vue
<script setup lang="ts">
import { HeaderTree } from "@reactivity-comparison/pivoting";
import Header from "./Header.vue";

type Props = {
  rows: HeaderTree[];
  offset: number;
  columnsDepth: number;
};
const { rows, offset, columnsDepth } = defineProps<Props>();
</script>

<template>
  <Header
    v-for="row in rows"
    :key="row.offset"
    :offset-x="offset"
    :offset-y="row.offset + columnsDepth"
    :size-x="1"
    :size-y="row.size"
    :value="row.value"
  ></Header>
  <Rows
    v-for="row in rows"
    :key="row.offset"
    :rows="row.children"
    :offset="offset + 1"
    :columns-depth="columnsDepth"
  ></Rows>
</template>

<style scoped></style>
