// stacks/vuejs/src/components/Cells.vue
<script setup lang="ts">
import { Line, Path } from "@reactivity-comparison/pivoting";
import CellWrapper from "./CellWrapper.vue";

type Props = {
  columnsPaths: Path[];
  rowsPaths: Path[];
  lines: Line[];
  rowsDepth: number;
  columnsDepth: number;
};
const { columnsPaths, rowsPaths, lines, rowsDepth, columnsDepth } =
  defineProps<Props>();
</script>

<template>
  <template v-for="(columnPath, columnIndex) in columnsPaths" :key="columnIndex"
    ><CellWrapper
      v-for="(rowPath, rowIndex) in rowsPaths"
      :key="rowIndex"
      :path-entries="[...columnPath.entries, ...rowPath.entries]"
      :lines="lines"
      :offset-x="columnPath.offset + rowsDepth"
      :offset-y="rowPath.offset + columnsDepth"
    ></CellWrapper
  ></template>
</template>

<style scoped></style>

// stacks/react/src/grid/internals/Cells.tsx
import { Fragment } from "react/jsx-runtime";
import {
  Line,
  Path,
  computeValue,
  filterLines,
  probeCall,
} from "@reactivity-comparison/pivoting";
import Cell from "./Cell";

type Props = {
  columnsPaths: Path[];
  rowsPaths: Path[];
  lines: Line[];
  rowsDepth: number;
  columnsDepth: number;
};

export default function Cells(props: Props) {
  probeCall(Cells.name);
  const { columnsPaths, rowsPaths, lines, rowsDepth, columnsDepth } = props;
  return (
    <>
      {columnsPaths.map((columnPath) => {
        const filteredLines = filterLines(columnPath.entries, lines);
        return (
          <Fragment key={columnPath.offset}>
            {rowsPaths.map((rowPath) => (
              <Cell
                key={rowPath.offset}
                value={computeValue(rowPath.entries, filteredLines)}
                offsetX={columnPath.offset + rowsDepth}
                offsetY={rowPath.offset + columnsDepth}
              />
            ))}
          </Fragment>
        );
      })}
    </>
  );
}
