// stacks/vuejs/src/components/Rows.vue
<script setup lang="ts">
import { HeaderSpanLevel } from "@reactivity-comparison/pivoting";
import Header from "./Header.vue";

type Props = {
  rowsSpans: HeaderSpanLevel[];
  columnsDepth: number;
};
const { rowsSpans, columnsDepth } = defineProps<Props>();
</script>

<template>
  <template v-for="(spanLevel, index) in rowsSpans" :key="index"
    ><Header
      v-for="span in spanLevel"
      :key="span.backingTree.offset"
      :offset-x="index"
      :offset-y="span.backingTree.offset + columnsDepth"
      :size-x="1"
      :size-y="span.backingTree.size"
      :value="span.backingTree.value"
    ></Header
  ></template>
</template>

<style scoped></style>

// stacks/react/src/grid/internals/Rows.tsx
import { Fragment } from "react/jsx-runtime";
import { HeaderSpanLevel, probeCall } from "@reactivity-comparison/pivoting";
import Header from "./Header";

type Props = {
  rowsSpans: HeaderSpanLevel[];
  columnsDepth: number;
};

export default function Rows(props: Props) {
  probeCall(Rows.name);
  const { rowsSpans, columnsDepth } = props;
  return (
    <>
      {rowsSpans.map((spanLevel, index) => (
        <Fragment key={index}>
          {spanLevel.map((span) => (
            <Header
              key={span.backingTree.offset}
              offsetX={index}
              offsetY={span.backingTree.offset + columnsDepth}
              sizeX={1}
              sizeY={span.backingTree.size}
              value={span.backingTree.value}
            />
          ))}
        </Fragment>
      ))}
    </>
  );
}
